name: Build and Test
 
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  test:
    strategy:
      matrix:
        node-version: [16.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Build
        run: |
          yarn install
          yarn build
