name: Build and Test
 
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  configure:

    permissions:
      contents: write
      pull-requests: write
      
    runs-on: ubuntu-latest
    # if: github.actor != 'dependabot[bot]'
    steps:
      - name: Pull request auto merge enabler
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        uses: poad/github-pull-request-auto-merge-enable-action@3a9b27f412592f0eb2cd6649509178e1fcaf3ccf # v3.0.2
        with:
          pull_request_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}
          merge_method: SQUASH

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 'lts/*'
          check-latest: true
          package-manager-cache: false

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        name: Install pnpm
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile, --strict-peer-dependencies]

      - name: Build
        run: pnpm build
